import express from "express";
import cors from "cors";
import authRoutes from "./routes/authRoutes.js";
import resumeRoutes from "./routes/resumeRoutes.js";
import jobmatchRoutes from "./routes/jobmatchRoutes.js"; // Fixed: lowercase 'm'
import interviewRoutes from "./routes/interviewRoutes.js";

const app = express();

// Middleware
// Replace your old cors middleware block completely with this:
app.use(
  cors({
    origin: function (origin, callback) {
      // Allows local testing OR any dynamic deployment generated by your Vercel account
      if (!origin || origin.includes("localhost") || origin.includes("vercel.app")) {
        callback(null, true);
      } else {
        callback(new Error("CORS Policy: This origin is not allowed by the backend."));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"]
  })
);

app.use(express.json());

app.use("/api/auth", authRoutes);
app.use("/api/resume", resumeRoutes);
app.use("/api/jobmatch", jobmatchRoutes); // Fixed: variable name changed to lowercase 'm'
app.use("/api/interview", interviewRoutes);

// Test route
app.get("/", (req, res) => {
  res.send("AI Career Prep Platform API is running 🚀");
});

export default app;
